version: '2.3'

services:
    mxnet-dev:
        image: mxnet-gpu:latest.100
        build:
            context: ./dockerfiles
            dockerfile: mxnet-cu100.Dockerfile
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
        privileged: true
        command: >
            bash -ce "cd /mnt/mxnet
                      make -j16 USE_CUDA=1 USE_CUDNN=1 \
                                USE_CUDA_PATH=/usr/local/cuda \
                                USE_LAPACK=1 \
                                USE_CPP_PACKAGE=1
                      chown -R $$(stat -c '%u:%g' /mnt) ."
