version: '2.3'

services:
    mxnet-dev:
        image: mxnet-gpu:latest.102
        build:
            context: ./dockerfiles
            dockerfile: mxnet-cu102.Dockerfile
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
        pid: host
        shm_size: 8g
