version: '2.3'

services:
    mxnet-dev:
        image: mxnet-gpu:latest.102
        build:
            context: ./dockerfiles
            dockerfile: mxnet-cu102.Dockerfile
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
        pid: host
        command: >
            bash -ce "cd /mnt/mxnet
                      make -j $$(nproc) USE_CUDA=1 USE_CUDNN=1 USE_NVML=1 \
                                        USE_CUDA_PATH=/usr/local/cuda \
                                        USE_JEMALLOC=1
                      chown -R $$(stat -c '%u:%g' /mnt) ."
