version: '2.3'

services:
    mxnet-cu90:
        image: mxnet-gpu:latest
        build:
            context: ./dockerfiles
            dockerfile: mxnet-cu90.Dockerfile
        volumes:
            - .:/mnt
        working_dir: /mnt
        command: >
            bash -c "set -e; 
                     cd /mnt/mxnet; make -j $$(nproc) USE_CUDA=1 \
                                                      USE_CUDA_PATH=/usr/local/cuda \
                                                      USE_CUDNN=1;
                     chown -R $$(stat -c '%u:%g' /mnt) .;"
    mxnet-cu100:
        image: mxnet-gpu:latest
        build:
            context: ./dockerfiles
            dockerfile: mxnet-cu100.Dockerfile
        volumes:
            - .:/mnt
        working_dir: /mnt
        command: >
            bash -c "set -e; 
                     cd /mnt/mxnet; make -j $$(nproc) USE_CUDA=1 \
                                                      USE_CUDA_PATH=/usr/local/cuda \
                                                      USE_CUDNN=1;
                     chown -R $$(stat -c '%u:%g' /mnt) .;"
